# Generated by Django 3.1 on 2020-09-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pick',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='select',
            field=models.CharField(choices=[['Blue', False], ['Red', True]], max_length=20),
        ),
    ]
