# Generated by Django 2.2.6 on 2019-11-09 19:30

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='articles/images'),
            preserve_default=False,
        ),
    ]
