# Generated by Django 2.2.5 on 2020-04-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='selecting',
            field=models.CharField(choices=[['A', False], ['B', True]], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
