# Generated by Django 2.2.5 on 2020-04-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie_title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
