# Generated by Django 2.2.4 on 2019-08-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
