# Generated by Django 2.2.4 on 2019-08-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(default='local', max_length=10),
            preserve_default=False,
        ),
    ]
