# Generated by Django 2.2.5 on 2019-11-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0003_patient_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(related_name='patients', through='manytomany.Reservation', to='manytomany.Doctor'),
        ),
    ]
