# Generated by Django 2.2.5 on 2019-09-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
