# Generated by Django 2.2.5 on 2019-10-08 07:17

import articles.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20191004_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=articles.models.articles_image_path),
        ),
    ]
